version: 'build-{build}-{branch}'

platform: x64

build:
  parallel: true

cache:
  - c:\tools\vcpkg\installed\ -> testing\dependencies\appveyor\install.bat
  - c:\msys64\var\cache\pacman\pkg -> testing\dependencies\appveyor\install.bat
  - c:\Deps\conda\ -> testing\dependencies\appveyor\anaconda.ps1

image:
  - Previous Visual Studio 2017

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: 'windows'
  CTEST_OUTPUT_ON_FAILURE: '1'
  matrix:
    - CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      BUILDFLAGS: '/verbosity:normal'
      TESTTARGET: 'RUN_TESTS'
    - CMAKE_GENERATOR: 'MSYS Makefiles'
      BUILDFLAGS: 'VERBOSE=1'
      TESTTARGET: 'test'

matrix:
  fast_finish: true

init:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  # Remove Python 2.7 from path
  - set PATH=%PATH:C:\Python27;=%
  - set PATH=%PATH:C:\Python27\Scripts;=%
  # Add Anaconda to PATH
  - set PATH=C:\Deps\conda\Scripts;C:\Deps\conda\library\bin;%PATH%

install:
  - python -m pip install pipenv
  - '%APPVEYOR_BUILD_FOLDER%\testing\dependencies\appveyor\install.bat'
  - ps: .$env:APPVEYOR_BUILD_FOLDER\testing\dependencies\appveyor\anaconda.ps1
  - pipenv install --three

# extract step has to happen before the sh.exe workaround otherwise 7z will complain
before_build:
  - pipenv run python --version
  - cmake --version

build_script:
  - bash -c "pipenv run python test.py"
  - bash -c "./custom.sh build_conda_mkl"

deploy: off
